name: Deploy Azure SQL Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/bd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Check if Resource Group exists and import it
      run: |
        RESOURCE_GROUP_ID="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/azurelab3powerbi-rg"
        if terraform state list azurerm_resource_group.rg > /dev/null; then
          echo "Resource group already managed by Terraform."
        else
          terraform import azurerm_resource_group.rg $RESOURCE_GROUP_ID
        fi
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: infra

    - name: Restore Database (using PowerShell)
      shell: pwsh
      run: ./scripts/restore_database.ps1
      env:
        AZURE_SQL_SERVER: ${{ secrets.SQL_SERVER_NAME }}
        AZURE_SQL_ADMIN: ${{ secrets.ADMIN_USERNAME }}
        AZURE_SQL_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
