name: Deploy Azure SQL Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/bd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Import existing resources if needed
      run: |
        # Intenta importar el recurso de SQL Server si no est√° en el estado de Terraform
        RESOURCE_ID="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/azurelab3powerbi-rg/providers/Microsoft.Sql/servers/azurelab3powerbi-server"
        terraform import azurerm_mssql_server.sql_server $RESOURCE_ID || echo "SQL Server already managed by Terraform"
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: infra

    - name: Restore Database (using PowerShell)
      shell: pwsh
      run: ./scripts/restore_database.ps1
      env:
        AZURE_SQL_SERVER: ${{ secrets.SQL_SERVER_NAME }}
        AZURE_SQL_ADMIN: ${{ secrets.ADMIN_USERNAME }}
        AZURE_SQL_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
