name: Deploy Azure SQL Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/bd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: infra/terraform


    - name: Restore Database (using PowerShell)
      shell: pwsh
      run: ./scripts/restore_database.ps1
      env:
        AZURE_SQL_SERVER: ${{ secrets.SQL_SERVER_NAME }}
        AZURE_SQL_ADMIN: ${{ secrets.ADMIN_USERNAME }}
        AZURE_SQL_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
